### ISSUE TITLE
use .editorconfig

### ISSUE THREAD

**Issue by mkuzak** [carpentries/styles#131]
Using [editorconfig](http://editorconfig.org/) will help with having more consistently edited files (tabs vs spaces etc.). The advantage is that it can store configuration for all used languages and file types so that we can have single `.editorconfig` file for all lessons. `.editorconfig` is recognised automatically by most popular text editors.

**Comment by katrinleinweber** [comment]
RStudio doesn't yet, but it's on the radar: https://github.com/rstudio/rstudio/issues/1711

**Comment by maxim-belkin** [comment]
Addressed in #216
