### ISSUE TITLE
redirecting gh-pages links

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/styles#189]
There's been some recent discussion around moving shared resources over to the joint carpentries github organization. At @rgaiacs's suggestion, I'm adding an issue here about a problem I ran into migrating the instructor-training repo.

See [here](https://github.com/swcarpentry/swcarpentry.github.io/pull/2) and [here](https://github.com/swcarpentry/swcarpentry.github.io/pull/3#issuecomment-342029043) for details about the problem.

**Comment by ErinBecker** [comment]
Useful resources:

[Redirecting GitHub Pages after a repository move](https://gist.github.com/domenic/1f286d415559b56d725bee51a62c24a7)

[About repository transfers](https://help.github.com/articles/about-repository-transfers/)

**Comment by fmichonneau** [comment]
I think we're now all set here.
