### ISSUE TITLE
Page build failure

### ISSUE THREAD

**Issue by rgaiacs** [carpentries/styles#207]
I get a email notification for every push that I do because we are using `gh-pages` for the branch.

> The page build failed for the `gh-pages` branch with the following error:
>
> Page build failed. For more information, see https://help.github.com/articles/troubleshooting-github-pages-builds/.
>
> For information on troubleshooting Jekyll see:
>
>  https://help.github.com/articles/troubleshooting-jekyll-builds
>
> If you have any questions you can contact us by replying to this email.

This is very annoying. The source of this problem is that GitHub will trigger a worker to run Jekyll for a branch `gh-pages` and we can't disable it. If we change the branch name to `master` it will disable the worker creation. Unfortunately this will mean that we need to change the instructions to use this repository from

~~~
$ git clone https://github.com/swcarpentry/styles/
$ cd styles
$ ./bin/lesson_initialize.py
~~~

to 

~~~
$ git clone https://github.com/swcarpentry/styles/
$ cd styles
$ git branch -m master gh-pages
$ ./bin/lesson_initialize.py
~~~

**Comment by rgaiacs** [comment]
swcarpentry/styles#287 will resolve this issue. :-)

**Comment by fmichonneau** [comment]
I agree with you @rgaiacs, it would be nice to not get these error messages. I'm going to move this issue to the 9.6.0 milestone as it requires a little more planning and communication around this change. But I agree we should move forward with #287.

**Comment by maxim-belkin** [comment]
Build fails because of three "missing" files:
- index.md
- CODE_OF_CONDUCT.md, and 
- setup.md

If we get rid of boilerplate directory and move these files to the root directory, builds will be successful (but we would still get notifications about them)

**Comment by fmichonneau** [comment]
we build a mock website from the `main` branch to avoid this now.
