### ISSUE TITLE
Add Docker suport to build the lesson to the makefile

### ISSUE THREAD

**Issue by iglpdc** [carpentries/styles#238]
Some contributors may want to use Docker to check and render the lesson locally instead of using an installation of jekyll. It could be useful for them to have the equivalent of `make serve` and `make build` that use a docker container instead of the local installation. The current commands will be still available.

- [ ] Add a target `docker-serve` that builds the lesson using a previously pulled docker container.
- [ ] Add a target `docker-build` that builds the lesson using a previously pulled docker container.
- [ ] Add a target `docker-pull` that pull the container.

This seems to work (pointed by @lexnederbragt on Slack):

```
docker run -p 4000:4000 --volume=${PWD}:/srv/jekyll -it jekyll/jekyll make serve
```

**Comment by gdevenyi** [comment]
Yes please!

I despise the mess that is a ruby install on Ubuntu.

**Comment by fpsom** [comment]
Agreed!

**Comment by lexnederbragt** [comment]
+1. But, isn't it going to be a problem when someone wants to render more than one site? They will then run into a `port is already allocated` error for the second one.

**Comment by alee** [comment]
Good idea! I was going the route of docker-compose / Dockerfile for the repo but I think this is simpler (assuming everyone has `make` installed). 

Just a minor note, it's good practice to pin the version on the docker image `jekyll/jekyll:3` or `jekyll/jekyll:3.8`

I think rendering more than one site isn't a big issue, just Ctrl-C the running container and spin up a new one in the new directory.

Are the pull and build targets necessary? The first one should automatically pull the referenced jekyll image and the build target is subsumed by `make serve`.

**Comment by gdevenyi** [comment]
We should pin the version to be the same as github pages (and move with their version) https://pages.github.com/versions/

**Comment by gdevenyi** [comment]
Maybe this? https://github.com/Starefossen/docker-github-pages

**Comment by iglpdc** [comment]
> Are the pull and build targets necessary? The first one should automatically pull the referenced jekyll image and the build target is subsumed by make serve.

You're right the pull is not needed. I'm not sure about the `build`: just though in having it by symmetry with the local installation case. I don't know about a use-case for `build` either: maybe in a script where you just want to generate the files?

**Comment by iglpdc** [comment]
We should also modify the build instructions ([here?](https://github.com/swcarpentry/lesson-example/blob/gh-pages/_episodes/07-checking.md)) to make people aware of this.

**Comment by alee** [comment]
I'd recommend staying with "official" images having been burned by references to community-contributed images in the past.

https://github.com/envygeeks/jekyll-docker

**Comment by gdevenyi** [comment]
@alee My recommendation of https://github.com/Starefossen/docker-github-pages was because its supposed to be the current state of github pages, which is how we eventually host the content.

**Comment by alee** [comment]
Understood, that's perfectly reasonable - was just a word of caution. FWIW the official jekyll image seems to build the swcarpentry sites without issue.

**Comment by fmichonneau** [comment]
we now have a good docker support in our makefile

**Comment by lexnederbragt** [comment]
I did a quick test and it works as expected. Thanks!
