### ISSUE TITLE
Mathjax support

### ISSUE THREAD

**Issue by bagustris** [carpentries/styles#296]
Just curious, does anyone has implementation to support Mathjax/Latex in this lesson template? As we are teacher/researcher used math equation mostly to formalize the problem. Some thing like `$...$ ` to write inline equation.

**Comment by vahtras** [comment]
See some previous discussion in https://github.com/carpentries/styles/issues/154

**Comment by bagustris** [comment]
Thanks, it works! The solution is simple just to add mathjax server link in the `_index/index.html`.

**Comment by rgaiacs** [comment]
You need to add the link to MathJax in https://github.com/carpentries/styles/blob/gh-pages/_layouts/base.html.
