### ISSUE TITLE
Pandoc 2.x

### ISSUE THREAD

**Issue by rgaiacs** [carpentries/styles#297]
As mentioned by [Yihui Xie](https://yihui.name/) in "[Okay, it is Time to Try Pandoc 2.x Now](https://yihui.name/en/2018/06/time-for-pandoc-2-x/)",

> If you use RStudio, you may consider trying the latest preview release of the RStudio IDE, in which we have bundled Pandoc 2.2.1, so you don’t need to install Pandoc separately.

For the R lessons, we use Pandoc to convert from R Markdown to Markdown that later will be converted to HTML by kramdown (used by Jekyll). I don't expect any major problem when moving from Pandoc 1.x to Pandoc 2.x but my recommendation is that swcarpentry/r-maintainers make a plan to start using Pandoc 2.x when building the website.

@fmichonneau I'm assigning this issue to you so that you can coordinate this. Thanks in advance.

**Comment by fmichonneau** [comment]
We currently don't use pandoc in our template. We only use knitr to convert from Rmd to md.
