### ISSUE TITLE
CODE_OF_CONDUCT.md is missing from root

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/styles#300]
the files are in bin/boilerplate, but they are getting deleted when merging the repository into existing lessons. They need to be added back in.

**Comment by rgaiacs** [comment]
> They need to be added back in.

This should be fixed downstream and not in this repository.

**Comment by fmichonneau** [comment]
for the aio.md file it was indeed because it was a very out of date repository that didn't have this file.

However, for `CODE_OF_CONDUCT.md`, when pulling the latest version of the template into an existing lesson, there is a commit that moves `CONDUCT.md` from the root of the repository to `bin/boilerplate/CODE_OF_CONDUCT.md` and effectively deletes the file from the root of repository if it was already there.

Given that all repositories should have the same version of this file, I suggest we put it back at the root of this repository for now. Moving to the 2-branch system will take care of this as well.
