### ISSUE TITLE
update .travis.yml to install most recent R version

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/styles#301]
see here: https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb

**Comment by fmichonneau** [comment]
That's what I normally use, but would this give us all the python tools needed for the lessons?
We need both python and R for our Travis builds.

**Comment by alee** [comment]
Ah right. We might be able to use the travis `matrix:include` to do this but now I understand why you linked the travis build script  :sweat_smile: 

Another option could be to set up the Docker image that has both Python + R embedded and use travis's docker support to build & run the make targets in that image.

**Comment by rgaiacs** [comment]
https://github.com/carpentries/styles/blob/gh-pages/bin/boilerplate/.travis.yml has our `.travis.yml`.

```
$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
$ echo "deb https://cran.rstudio.com/bin/linux/ubuntu trusty/" | sudo tee -a /etc/apt/sources.list
$ sudo apt-get update -y
$ sudo apt-get install -y r-base
```

were added to install the most recent R version (at least the one provided by RStudio to Ubuntu Trusty).

**Comment by fmichonneau** [comment]
We are now using GitHub Actions.
