### ISSUE TITLE
Software Carpentry page goes into a redirect loop

### ISSUE THREAD

**Issue by trk9001** [carpentries/styles#312]
https://github.com/carpentries/styles/blob/d2b83c815a32c3e7eba006f579dc4ba37bc4dfcc/bin/boilerplate/_config.yml#L40

The above link in `_config.yml` redirects to https://software-carpentry.org/lessons.html which then gets stuck in a redirect loop. Maybe the intended page is at https://software-carpentry.org/lessons/?

**Comment by fmichonneau** [comment]
thanks for letting us know!
