### ISSUE TITLE
Are these styles for lesson sites?

### ISSUE THREAD

**Issue by maneesha** [carpentries/styles#314]
The description for this repo reads:

> Styles  for SWC/DC sites. Documentation at http://carpentries.github.io/lesson-example/.

Should this read "Styles for SWC/DC lesson sites" ? This would make it clear that it is for the lesson pages, not the web sites.  

Will all SWC/DC lessons use this template?  Currently these pages use a different template:
http://www.datacarpentry.org/R-ecology-lesson/
http://www.datacarpentry.org/R-genomics/

**Comment by fmichonneau** [comment]
Thanks @maneesha, I updated the description to "Styles for The Carpentries lessons".

Yes, these 2 lessons use a different template which has been a testing ground for other features. All others lessons (including LC) use this template.
