### ISSUE TITLE
Copyright/footer on all Carpentries lesson pages?

### ISSUE THREAD

**Issue by maneesha** [carpentries/styles#315]
Should this:

> Copyright © 2018–2018 The Carpentries

be the footer for all our lessons (across Carpentries)?  
Some lessons (such as http://swcarpentry.github.io/git-novice/ and http://www.datacarpentry.org/genomics-workshop/) include "Software Carpentry Foundation" or "Data Carpentry" copyright as well.  Some have only "The Carpentries" copyright.

Also can we make the copyright line read something like this what's on the handbook (https://docs.carpentries.org/) to make it clear this is an open license, not a strict traditional copyright?

**Comment by rgaiacs** [comment]
> Should this (...) be the footer for all our lessons (across Carpentries)?

**Yes**.

> Some lessons (such as http://swcarpentry.github.io/git-novice/ and http://www.datacarpentry.org/genomics-workshop/) include "Software Carpentry Foundation" or "Data Carpentry" copyright as well. Some have only "The Carpentries" copyright.

Please see https://github.com/carpentries/styles/blob/gh-pages/_includes/lesson_footer.html for the implementation. We should be more accurate with the begin of the copyright but do it in Jekyll for the number of lessons that we have is hard so we are using the begin of the projects. Software Carpentry and Data Carpentry lessons have additional copyright for the time that The Carpentries didn't exist.

> Also can we make the copyright line read something like this what's on the handbook (https://docs.carpentries.org/) to make it clear this is an open license, not a strict traditional copyright?

We have https://carpentries.github.io/lesson-example/LICENSE.html. Although the lessons are CC-BY  we have some trademark rules so I'm more confortable to not include the "This content is released under the terms of the Creative Commons Attribution License."

**Comment by fmichonneau** [comment]
addressed with https://github.com/carpentries/styles/commit/887f484d746c0547478f8da8ae53de4774c7bbea
