### ISSUE TITLE
"wrong" link on deprecated swcarpentry/DEPRECATED-lesson-template description

### ISSUE THREAD

**Issue by yarikoptic** [carpentries/styles#363]
Since that one is read only, cannot file an issue there.
Description for that repo points to the swcarpentry/styles but that one was moved (?) under this organization. Confusion comes if someone starts to search for "styles" within swcarpentry list of repositories (redirect if typed into url works fine)

**Comment by brownsarahm** [comment]
Broken links within a deprecated repo are unavoidable.  We could maybe add to the readme or github description pointing to the correct repo.  Can you describe what you were trying to do when you found the broken links?

**Comment by yarikoptic** [comment]
yes, I just meant to ask to change description on https://github.com/swcarpentry/DEPRECATED-lesson-template
from

DEPRECATED: THIS REPOSITORY IS NO LONGER IN USE: PLEASE SEE swcarpentry/styles INSTEAD.

to

DEPRECATED: THIS REPOSITORY IS NO LONGER IN USE: PLEASE SEE carpentries/styles INSTEAD.

**Comment by brownsarahm** [comment]
That one was deprecated 3 years ago, so multiple changes have happened since then.  If anything points there, we should fix that. How did you end up at the deprecated lesson example?

**Comment by rgaiacs** [comment]
Thanks for the issue. Because the reported repository is archived we can't change the content. I'm closing this issue.
