### ISSUE TITLE
Change 'coffee' to breaks to be more inclusive

### ISSUE THREAD

**Issue by lexnederbragt** [carpentries/styles#367]
I don't have push rights, so I'm lazy and will refer to other similar PRs. The idea is that not everyone drinks coffee, or even tea, and there may be cultural differences/sensitivities around this too.

Suggestion is to change 'Coffee' in the schedule to 'Morning break' or 'Afternoon break', as in https://github.com/carpentries/workshop-template/pull/557 and https://github.com/carpentries/instructor-training/pull/810

**Comment by rgaiacs** [comment]
@lexnederbragt I like to use the word "Refreshments" instead of 'Morning break' or 'Afternoon break'.

@ChristinaLK, @raynamharris and @ErinBecker what do you thing?

**Comment by fmichonneau** [comment]
this has been addressed.
