### ISSUE TITLE
using a .github directory for more community health files

### ISSUE THREAD

**Issue by raynamharris** [carpentries/styles#389]
I saw this blog post the other day, and I thought it could be useful for us. https://github.blog/changelog/2019-02-21-organization-wide-community-health-files/

Briefly, you can add README, CONTRIBUTING, SUPPORT, CODE_OF_CONDUCT, ISSUE_TEMPLATE(S), or PULL_REQUEST_TEMPLATE(S) files to a public, organization-owned .github repository, and if a given community health file doesn’t exist for a repository, the organization-wide default will be used.

Would it make sense to move the CONTRIBUTING and CODE_OF_CONDUCT files to .github so that these appear in all Carpentries repos?

**Comment by katrinleinweber** [comment]
`CONTRIBUTING` information may be a bit different whether its a workshop site or a lesson, but IMHO it's better to bundle there, then in each repo individually.

**Comment by fmichonneau** [comment]
We now have:

- https://github.com/carpentries/.github
- https://github.com/datacarpentry/.github
- https://github.com/swcarpentry/.github
- https://github.com/librarycarpentry/.github

populated with default files, so any repository in each organization will have the correct files.
