### ISSUE TITLE
Proposed changes to code and output blocks

### ISSUE THREAD

**Issue by maxim-belkin** [carpentries/styles#392]
Using CSS we can add explanatory text before code and output cells like so:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/13123663/54108177-40f76580-43a9-11e9-9bad-f5ade3832391.png">

Will this improve code/output blocks?
The page I used to create the above example is https://swcarpentry.github.io/python-novice-inflammation/03-lists/index.html

**Comment by rgaiacs** [comment]
> Will this improve code/output blocks?

I think so.

**Comment by fmichonneau** [comment]
this looks good!

**Comment by maxim-belkin** [comment]
Submitted a PR carpentries/styles#393

**Comment by maxim-belkin** [comment]
Closed in 514fb46
