### ISSUE TITLE
"SC" and "SWC" acronyms are used inconsistently in documentation

### ISSUE THREAD

**Issue by pkrafft** [carpentries/styles#399]
Point 5 in "Customizing Your Website" in README.md uses the acronyms "dc" (Data Carpentry workshop), "lc" (Library Carpentry), or "sc" (Software Carpentry) for their subdirectories.

However, the _config.yml file indicates:

Which carpentry is this ("swc", "dc", "lc", or "cp")?
swc: Software Carpentry
dc: Data Carpentry
lc: Library Carpentry
cp: Carpentries (to use for instructor traning for instance)

And uses "swc" in names such as "swc_github" throughout.

Fixing this issue would require selecting sc or swc as conventional and then using that acronym throughout all documentation.

**Comment by fmichonneau** [comment]
@maneesha, is this something you could look into and fix? Thanks!

**Comment by maneesha** [comment]
@fmichonneau  Is there a reason to prefer one or the other?  I think we should do 'swc` since that's how we refer to it in most other places.  Let me know if there's a reason we may want to consider 'sc' instead.

**Comment by fmichonneau** [comment]
I agree I think we should prefer `swc`. I think sc was chosen because it was 2-character long and lined up with `dc`. Thank you!

**Comment by maneesha** [comment]
@fmichonneau can this be closed now?

**Comment by fmichonneau** [comment]
it will get closed when the commit above is merged. It's part of a PR that is still work in progress at this stage.
