### ISSUE TITLE
Change point of contact for PR and issue templates

### ISSUE THREAD

**Issue by k8hertweck** [carpentries/styles#400]
A few years back, when I was actively involved in the maintainer community, I wrote the original PR and issue templates and offered myself as a point of contact for anyone with questions about the process (I've included the text of the current issue template below for easy reference; the PR template is largely the same, if not identical).

Two things:
1. I'm not the best person for folks to contact to get involved. I only get an email once every few months, and they're usually easy to handle, but this would be better suited for one of the Carpentries staff emails.
2. The rest of the text of this template could use some tweaking. For example, "contribution reviewer" is listed as a role that may or may not be relevant anymore.

Please delete this line and the text below before submitting your contribution.

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

If this issue is about a specific episode within a lesson, please provide its link or filename.

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck (k8hertweck@gmail.com).  

---

**Comment by maneesha** [comment]
@ErinBecker   Can this go to team@carpentries.org instead of Kate?

**Comment by raynamharris** [comment]
I replaced "Kate Hertweck (k8hertweck@gmail.com)" with "The Carpentries Team at team@carpentries.org"

**Comment by fmichonneau** [comment]
fixed with #401
