### ISSUE TITLE
Fix figure paths in aio.md

### ISSUE THREAD

**Issue by humburg** [carpentries/styles#420]
While trying to use the *All in one page* feature I noticed that all the images were missing. The reason seems to be that `aio.md` is located at the top-level whereas the episodes are in their own sub-directory, which results in incorrect relative paths. 

For the figures that could be fixed by replacing

```js
article_here.innerHTML = htmlDocArticle.innerHTML;
```

with something like

```js
article_here.innerHTML = htmlDocArticle.innerHTML.replace(/"\.\.\/fig\//, "\"fig/" );
```

Are there other situations where episodes might employ relative paths that should be fixed up? I'm happy to submit a pull request but wanted to see whether a more general solution might be required (or whether there might be other issues I'm missing).

**Comment by humburg** [comment]
Ah, I didn't realise where this was coming from. I was looking at [https://github.com/datacarpentry/r-socialsci](https://github.com/datacarpentry/r-socialsci) but that doesn't seem to be using the new styles. It does indeed look like it is working in the current version.

**Comment by fmichonneau** [comment]
@humburg can we close this?

**Comment by humburg** [comment]
Yes sorry, I meant to close this with my previous comment but evidently forgot.
