### ISSUE TITLE
Blockquote paragraphs lack proper space

### ISSUE THREAD

**Issue by kekoziar** [carpentries/styles#423]
The paragraphs that are within blockquotes (callouts, exercises, etc) lack proper spacing between them, such that it looks like one long paragraph.  Adding 
`blockquote p { padding-bottom: inherit; }`
to `bootstrap.css` should fix the issue.

**Comment by maxim-belkin** [comment]
seems reasonable. Could you please submit a PR with a screenshot before and after

**Comment by maxim-belkin** [comment]
Fixed in #425.
