### ISSUE TITLE
.python code blocks

### ISSUE THREAD

**Issue by maxim-belkin** [carpentries/styles#427]
See https://github.com/swcarpentry/python-novice-inflammation/pull/701

`.python` (and I assume other language blocks) are not rendered as they should. I assume [rouge](https://github.com/rouge-ruby/rouge#jekyll) that GitHub uses is at fault but... I'm not 100% sure.

I'll look into this when I have the time but if anyone else would like to investigate this -- be my guest.

**Comment by fmichonneau** [comment]
@maxim-belkin feel free to re-open if you think there is a bug here.
