### ISSUE TITLE
Update boilerplate .travis.yml to fix unauthenticated packages error

### ISSUE THREAD

**Issue by agitter** [carpentries/styles#429]
I'd like to make a small pull request to fix a Travis CI error I encountered when running the boilerplate `.travis.yml` in a new lesson repository.  First, I wanted to make sure I understood the file organization in this repository and purpose of Travis CI on lessons.  Is it correct that Travis CI is only used to check the correctness of the lesson?  It is not involved in the lesson deployment?

The specific error message is
```
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
The command "sudo apt-get install -y r-base" failed and exited with 100 during .
```

Adding this argument was sufficient for the build to pass https://github.com/gitter-lab/ml-bio-workshop/commit/ff735fa63e9bef692a5e0fb6b8fb20bbca42e744

A bigger picture question is whether this boilerplate `.travis.yml` is run anywhere to make sure that the build process doesn't break.

**Comment by fmichonneau** [comment]
Hi @agitter, thanks for spotting this. Yes, Travis here is only used to check the lesson and is not involved in its deployment. 

It looks like with the current Travis file we are using a very old version of R. We should update the Travis script to use a more recent version of R following the instructions here: https://cran.r-project.org/bin/linux/ubuntu/README.html
