### ISSUE TITLE
update license and trademark things

### ISSUE THREAD

**Issue by raynamharris** [carpentries/styles#444]
A few issues have come up in Instructor training about licenses and trademarks (e.g. https://github.com/carpentries/instructor-training/issues/1041 and https://github.com/carpentries/instructor-training/issues/1044 and https://github.com/carpentries/instructor-training/pull/1054) I think the LICENSE file in other repositories comes from here, but I could be incorrect.

One question I have is whether the listing of trademarks is limited to the 3 lesson programs or if it should include the umbrella Carpentris organization as well.

**Comment by brownsarahm** [comment]
I moved instructor-training#1041 to this repo, so closing this one as redundant.
