### ISSUE TITLE
carpentries/styles for maintainers

### ISSUE THREAD

**Issue by maxim-belkin** [carpentries/styles#466]
Can we turn off building carpentries/styles from the gh-pages branch as described in https://help.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a-publishing-source ?

**Comment by fmichonneau** [comment]
ok, I created an orphan `master` branch with a basic README and switched the default branch for building the site, so I think that should stop the building failure emails...
