### ISSUE TITLE
leave more space under code blocks

### ISSUE THREAD

**Issue by btel** [carpentries/styles#93]
The content directly under code blocks in examples and exercises has too little vertical space, so it looks crammed. See the lines starting with "Hint:" and "Solution:" below.

[![space](https://cloud.githubusercontent.com/assets/41565/18026846/3bf8903e-6c53-11e6-8c5f-34dc585dc91c.png)](http://swcarpentry.github.io/python-novice-inflammation/03-lists/#turn-a-string-into-a-list)

Rendered under FF 48.0 on Ubuntu.

**Comment by rgaiacs** [comment]
The same happens with Chrome:

![screenshot_2016-08-27_14-26-10](https://cloud.githubusercontent.com/assets/1506457/18027682/45e4c63a-6c62-11e6-8307-f0baeb4e265f.png)

**Comment by rgaiacs** [comment]
This can be solved including something like

~~~
div.python.highlighter-rouge + blockquote.solution {
    margin-top: 10px;
}
~~~

on the CSS.

**Comment by maxim-belkin** [comment]
I believe this issue has been resolved:
![Screenshot of "Turn a string into a list" exercise](https://user-images.githubusercontent.com/13123663/93249060-94d4ce80-f745-11ea-8469-6a715bae623a.png)
